### PR TITLE
Ross

### PR DESCRIPTION
**Pull request by ross-hull**
create a function to get the latest resource id. This is useful for datasets that upload new resources each month instead of replacing old ones, for example GP practice contact details - https://www.opendata.nhs.scot/dataset/gp-practice-contact-details-and-list-sizes

### CODE REVIEW

**Comment by csillasch** [comment]
Looks good Ross, couple of thoughts:
- don`t need to use ckanr setup as the PHS_GET call points to the phs open data site by default
- don`t think we need the second package_show API call either as the first one returns all the resource metadata already

My bigger question is whether the dates will always be reliable enough for us to use in this way. Eg. an older resource might get updated due to a revision. Using created date might resolve that, but there might still be some niche cases where it`s misleading/fails - I`m thinking for example if a new dataset gets created and a number of resources are uploaded at the same time.

**Comment by Moohan** [comment]
I agree with Csilla's comments, this is a good/useful addition but we should be able to implement it without depending on ckanr.

As a user I don't think I'd be interested in the res-id, I'd just want the actual data, happy for you to disagree on that though!

We would still need something like `get_latest_resource_id()` it just wouldn't need to be exported, we'd then need an extra (exported) function.

```r
#' Get the latest Open Data resource from a dataset
#'
#' @description Returns the resource (data)
#' that was uploaded to a dataset most recently.
#'
#' @inheritParams get_dataset
#'
#' @inherit get_resource returns
#'
#' @export
get_latest_resource(dataset_name) {
    res_id <- get_latest_resource_id(dataset_name)
    data <- get_resource(res_id)
    return(data)
}
```

**Comment by ross-hull** [comment]
Thanks for the feedback. I see James has opened a pull request to add dates to get_dataset which perhaps could be used instead of the ckanr package

**Comment by ross-hull** [comment]
will close this pull request and open a new pull request for implementation that doesn't use any additional dependencies

**Pull request closed without merging**
